// js/data.js

// This array holds all the product information for our store.
// In a real-world application, this data would come from a server or a database.
const products = [
    // Apparel
    { id: 1, name: "Classic Leather Jacket", brand: "Urban Explorer", price: 16599, rating: 4.7, category: "Apparel", images: { black: ['https://images.pexels.com/photos/1124465/pexels-photo-1124465.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "A timeless jacket.", specifications: "Material: Leather." },
    { id: 4, name: "Linen Blend Shirt", brand: "Breezy Wear", price: 4899, rating: 4.6, category: "Apparel", images: { sky: ['https://images.pexels.com/photos/4066290/pexels-photo-4066290.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Perfect for summer.", specifications: "Material: Linen/Cotton." },
    { id: 5, name: "Denim Jeans", brand: "Rugged Fit", price: 5299, rating: 4.5, category: "Apparel", images: { blue: ['https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Durable and stylish.", specifications: "Material: Denim." },
    { id: 6, name: "Wool Peacoat", brand: "Gentleman's Choice", price: 19999, rating: 4.8, category: "Apparel", images: { navy: ['https://images.pexels.com/photos/1356273/pexels-photo-1356273.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Elegant winter wear.", specifications: "Material: Wool." },
    { id: 7, name: "Cotton T-Shirt Pack", brand: "Basics Co.", price: 2999, rating: 4.9, category: "Apparel", images: { multi: ['https://images.pexels.com/photos/4065187/pexels-photo-4065187.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "A pack of 3 essential tees.", specifications: "Material: 100% Cotton." },
    { id: 8, name: "Trench Coat", brand: "London Fog", price: 24999, rating: 4.7, category: "Apparel", images: { beige: ['https://images.pexels.com/photos/2895843/pexels-photo-2895843.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Classic and sophisticated.", specifications: "Material: Gabardine." },
    { id: 9, name: "Cashmere Sweater", brand: "Luxe Knits", price: 18999, rating: 4.9, category: "Apparel", images: { grey: ['https://images.pexels.com/photos/2043590/pexels-photo-2043590.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Incredibly soft and warm.", specifications: "Material: 100% Cashmere." },
    { id: 10, name: "Polo Shirt", brand: "Preppy Style", price: 3999, rating: 4.6, category: "Apparel", images: { red: ['https://images.pexels.com/photos/1240892/pexels-photo-1240892.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "A versatile wardrobe staple.", specifications: "Material: Pique Cotton." },
    { id: 11, name: "Chino Trousers", brand: "Smart Casual", price: 4599, rating: 4.5, category: "Apparel", images: { khaki: ['https://images.pexels.com/photos/5211446/pexels-photo-5211446.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Perfect for any occasion.", specifications: "Material: Cotton Twill." },
    { id: 12, name: "Hooded Sweatshirt", brand: "Cozy Wear", price: 5999, rating: 4.8, category: "Apparel", images: { black: ['https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Ultimate comfort and style.", specifications: "Material: Fleece." },

    // Accessories
    { id: 2, name: "Chrono Watch", brand: "Timeless Co.", price: 12499, rating: 4.9, category: "Accessories", images: { silver: ['https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Sleek and modern.", specifications: "Material: Stainless Steel." },
    { id: 13, name: "Leather Belt", brand: "Strap Up", price: 3499, rating: 4.7, category: "Accessories", images: { brown: ['https://images.pexels.com/photos/984619/pexels-photo-984619.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "A classic accessory.", specifications: "Material: Genuine Leather." },
    { id: 14, name: "Silk Tie", brand: "Sharp Dressed", price: 2999, rating: 4.8, category: "Accessories", images: { blue: ['https://images.pexels.com/photos/1684313/pexels-photo-1684313.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Elegant and professional.", specifications: "Material: 100% Silk." },
    { id: 15, name: "Wayfarer Sunglasses", brand: "Sunnies", price: 4999, rating: 4.6, category: "Accessories", images: { black: ['https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Iconic and stylish.", specifications: "Material: Acetate." },
    { id: 16, name: "Canvas Backpack", brand: "Carry All", price: 6999, rating: 4.7, category: "Accessories", images: { green: ['https://images.pexels.com/photos/1545346/pexels-photo-1545346.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Durable and spacious.", specifications: "Material: Waxed Canvas." },
    { id: 17, name: "Leather Wallet", brand: "Hold It", price: 3999, rating: 4.9, category: "Accessories", images: { black: ['https://images.pexels.com/photos/163037/luxury-watch-watch-time-clock-163037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Slim and functional.", specifications: "Material: Full-Grain Leather." },
    { id: 18, name: "Knit Beanie", brand: "Warm Head", price: 1999, rating: 4.8, category: "Accessories", images: { grey: ['https://images.pexels.com/photos/1721941/pexels-photo-1721941.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Stay warm in winter.", specifications: "Material: Merino Wool." },
    { id: 19, name: "Silver Cufflinks", brand: "Gentleman's Choice", price: 4599, rating: 4.9, category: "Accessories", images: { silver: ['https://images.pexels.com/photos/544112/pexels-photo-544112.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "A touch of class.", specifications: "Material: Sterling Silver." },
    { id: 20, name: "Travel Duffel Bag", brand: "Wanderer", price: 8999, rating: 4.7, category: "Accessories", images: { brown: ['https://images.pexels.com/photos/129759/pexels-photo-129759.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Your perfect travel companion.", specifications: "Material: Leather & Canvas." },
    { id: 21, name: "Patterned Socks", brand: "Happy Feet", price: 1499, rating: 4.8, category: "Accessories", images: { multi: ['https://images.pexels.com/photos/5861343/pexels-photo-5861343.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Add a pop of color.", specifications: "Material: Combed Cotton." },

    // Footwear
    { id: 3, name: "Canvas Sneakers", brand: "Streetwise", price: 6599, rating: 4.5, category: "Footwear", images: { white: ['https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Comfortable and stylish.", specifications: "Material: Canvas." },
    { id: 22, name: "Leather Brogues", brand: "Dapper Dan", price: 14999, rating: 4.8, category: "Footwear", images: { brown: ['https://images.pexels.com/photos/267202/pexels-photo-267202.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Classic dress shoes.", specifications: "Material: Calfskin Leather." },
    { id: 23, name: "Suede Loafers", brand: "Easy Stride", price: 11999, rating: 4.7, category: "Footwear", images: { navy: ['https://images.pexels.com/photos/1032117/pexels-photo-1032117.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Smart casual essential.", specifications: "Material: Suede." },
    { id: 24, name: "Hiking Boots", brand: "Trail Blazer", price: 18999, rating: 4.9, category: "Footwear", images: { brown: ['https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "For the great outdoors.", specifications: "Material: Waterproof Leather." },
    { id: 25, name: "Running Shoes", brand: "Quick Step", price: 9999, rating: 4.6, category: "Footwear", images: { blue: ['https://images.pexels.com/photos/1032110/pexels-photo-1032110.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Lightweight and responsive.", specifications: "Material: Mesh Upper." },
    { id: 26, name: "Chelsea Boots", brand: "Urban Explorer", price: 15999, rating: 4.7, category: "Footwear", images: { black: ['https://images.pexels.com/photos/167706/pexels-photo-167706.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Sleek and versatile.", specifications: "Material: Leather." },
    { id: 27, name: "Flip Flops", brand: "Beach Day", price: 1999, rating: 4.5, category: "Footwear", images: { blue: ['https://images.pexels.com/photos/1661905/pexels-photo-1661905.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Relaxed and comfortable.", specifications: "Material: Rubber." },
    { id: 28, name: "Oxford Shoes", brand: "Formal Attire", price: 13999, rating: 4.8, category: "Footwear", images: { black: ['https://images.pexels.com/photos/450212/pexels-photo-450212.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "The definitive dress shoe.", specifications: "Material: Patent Leather." },
    { id: 29, name: "Boat Shoes", brand: "Seafarer", price: 8999, rating: 4.6, category: "Footwear", images: { brown: ['https://images.pexels.com/photos/206584/pexels-photo-206584.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "Perfect for a day by the water.", specifications: "Material: Leather." },
    { id: 30, name: "Desert Boots", brand: "Nomad", price: 12999, rating: 4.7, category: "Footwear", images: { sand: ['https://images.pexels.com/photos/425297/pexels-photo-425297.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'] }, description: "A timeless casual boot.", specifications: "Material: Suede." }
];

// We use 'export' to make the products array available to other JavaScript files.
export { products };
